version: '2'

services:
  database:
    image: mariadb:10
    environment:
      - MYSQL_USER=sequelize_test
      - MYSQL_PASSWORD=lollerskates
      - MYSQL_DATABASE=sequelize_test
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: always
    ports:
    - 3306:3306
